---
# for the time being let's keep this simple
- name: Include OS-specific variables.
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Ensure samba is running
  ansible.builtin.service:
    name: "{{ samba_daemon }}"
    state: started
    enabled: yes

- name: Copy smb.conf over to remote host
  ansible.builtin.copy:
    src: "{{ samba_config_file_path }}"
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: 0600
    backup: yes
  notify: "Restart samba"
