---
# https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#installing-roles
- name: richardskumat.ansible_role_samba
  src: https://github.com/richardskumat/ansible-role-samba
  version: master
